/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AddFriendIndexRouteImport } from './routes/add-friend/index'
import { Route as ChatIndexRouteImport } from './routes/chat/index'
import { Route as ChatFriendIdRouteImport } from './routes/chat/$friendId'
import { Route as MeetingIndexRouteImport } from './routes/meeting/index'
import { Route as MeetingRoomIdRouteImport } from './routes/meeting/$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFriendIndexRoute = AddFriendIndexRouteImport.update({
  id: '/add-friend/',
  path: '/add-friend/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatIndexRoute = ChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatFriendIdRoute = ChatFriendIdRouteImport.update({
  id: '/chat/$friendId',
  path: '/chat/$friendId',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingIndexRoute = MeetingIndexRouteImport.update({
  id: '/meeting/',
  path: '/meeting/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingRoomIdRoute = MeetingRoomIdRouteImport.update({
  id: '/meeting/$roomId',
  path: '/meeting/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/meeting/$roomId': typeof MeetingRoomIdRoute
  '/add-friend/': typeof AddFriendIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/meeting/': typeof MeetingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/meeting/$roomId': typeof MeetingRoomIdRoute
  '/add-friend': typeof AddFriendIndexRoute
  '/chat': typeof ChatIndexRoute
  '/meeting': typeof MeetingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat/$friendId': typeof ChatFriendIdRoute
  '/meeting/$roomId': typeof MeetingRoomIdRoute
  '/add-friend/': typeof AddFriendIndexRoute
  '/chat/': typeof ChatIndexRoute
  '/meeting/': typeof MeetingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat/$friendId'
    | '/meeting/$roomId'
    | '/add-friend/'
    | '/chat/'
    | '/meeting/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat/$friendId'
    | '/meeting/$roomId'
    | '/add-friend'
    | '/chat'
    | '/meeting'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/chat/$friendId'
    | '/meeting/$roomId'
    | '/add-friend/'
    | '/chat/'
    | '/meeting/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ChatFriendIdRoute: typeof ChatFriendIdRoute
  MeetingRoomIdRoute: typeof MeetingRoomIdRoute
  AddFriendIndexRoute: typeof AddFriendIndexRoute
  ChatIndexRoute: typeof ChatIndexRoute
  MeetingIndexRoute: typeof MeetingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-friend/': {
      id: '/add-friend/'
      path: '/add-friend'
      fullPath: '/add-friend/'
      preLoaderRoute: typeof AddFriendIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/': {
      id: '/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ChatIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat/$friendId': {
      id: '/chat/$friendId'
      path: '/chat/$friendId'
      fullPath: '/chat/$friendId'
      preLoaderRoute: typeof ChatFriendIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/': {
      id: '/meeting/'
      path: '/meeting'
      fullPath: '/meeting/'
      preLoaderRoute: typeof MeetingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meeting/$roomId': {
      id: '/meeting/$roomId'
      path: '/meeting/$roomId'
      fullPath: '/meeting/$roomId'
      preLoaderRoute: typeof MeetingRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ChatFriendIdRoute: ChatFriendIdRoute,
  MeetingRoomIdRoute: MeetingRoomIdRoute,
  AddFriendIndexRoute: AddFriendIndexRoute,
  ChatIndexRoute: ChatIndexRoute,
  MeetingIndexRoute: MeetingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
